baseURL: https://mdlcs.dev/
languageCode: es-ES
title: mdlcs.dev
theme: PaperModX
paginate: 10
minify:
  disableXML: true
  minifyOutput: true
params:
  homeInfoParams:
    Title: |-
      Â¡Hola! ğŸ‘‹ğŸ» Soy Marcos 
        
        {y soy desarrollador de software}
    Content: "
      \  â˜•â€â€â€ â€ He desarrollado mi carrera con Java / Spring 
      y ahora trabajo con lenguajes como Kotlin y tecnologÃ­as como Postgres, Kafka o Redis.


      \  ğŸ§°â€â€â€ â€ La automatizaciÃ³n, el CI/CD y el cloud me encantan; por
      ello me escucharÃ¡s a menudo hablar de Github Actions, Sonar o proveedores como AWS.


      \  ğŸ¦„ â€ Me gustan mucho los temas relacionados con arquitectura y buenas prÃ¡cticas 
      asÃ­ que no dudes en charlar conmigo sobre arquitecturas limpias, SOLID o DDD.


      \  ğŸ¤¯â€â€â€ â€  Soy un apasionado de la tecnologÃ­a aparte de Ã¡vido
      lector y profesional del sarcasmo.

      
      \  --

      
      \  ğŸ‘‡ğŸ» â€ MÃ¡s informaciÃ³n aquÃ­.

      \  "
  socialIcons:
    - name: linkedin
      url: https://www.linkedin.com/in/marcosdlcs/
    - name: github
      url: https://github.com/marcosDLCS
    - name: telegram
      url: https://t.me/marcosDLCS  
outputs:
  home:
    - HTML
    - RSS
    - JSON
menu:
  main:
    - identifier: books
      name: Club de lectura
      url: /books
      weight: 1
    - identifier: mentoring
      name: MentorÃ­a
      url: /mentoring
      weight: 2  
    - identifier: more-content
      name: MÃ¡s contenido
      url: /more-content
      weight: 3
    - identifier: search
      name: Buscar
      url: /search
      weight: 4
