baseURL = "https://mdlcs.dev/"
languageCode = "es-ES"
title = "mdlcs.dev"
theme = "PaperMod"
paginate = 5

[minify]
disableXML = true
minifyOutput = true

[params.homeInfoParams]
  Title = """Â¡Hola! Soy Marcos ğŸ‘¨ğŸ»â€ğŸ’» 
  
  {y soy desarrollador de software}"""
  Content = """

  â˜•â€â€â€ â€ He desarrollado mi carrera principalmente en el ecosistema Java / Spring aunque he tenido que lidiar tambiÃ©n con tecnologÃ­as web como HTML, CSS, Javascript o Angular.
  
  --

  ğŸ§°â€â€â€ â€ La automatizaciÃ³n y el CI/CD son otro aspecto importante para mi; por ello me escucharÃ¡s a menudo hablar de Jenkins o SonarQube o sobre diferentes plataformas como AWS, Azure o GCP.

  --

  ğŸ¦„ â€ Me encantan los temas relacionados con arquitectura, buenas prÃ¡cticas o patrones, asÃ­ que no dudes en charlar conmigo sobre DDD, arquitectura hexagonal o SOLID.
  
  --

  ğŸ¤¯â€â€â€ â€  Soy un apasionado de la tecnologÃ­a aparte de Ã¡vido lector y profesional del sarcasmo.
  
  --
  
  ğŸ‘‡ğŸ» â€ MÃ¡s informaciÃ³n aquÃ­.
  """

  [[params.socialIcons]]
  name = "twitter"
  url = "https://twitter.com/marcosDLCS"

  [[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/marcosdlcs/"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/marcosDLCS"
