baseURL = "https://mdlcs.dev/"
languageCode = "es-ES"
title = "mdlcs.dev"
theme = "PaperMod"
paginate = 5

[minify]
disableXML = true
minifyOutput = true

[params.homeInfoParams]
  Title = """Â¡Hola! ğŸ‘‹ğŸ» Soy Marcos 
  
  {y soy desarrollador de software}"""
  Content = """

  â˜•â€â€â€ â€ He desarrollado mi carrera en el ecosistema Java / Spring y he lidiado con tecnologÃ­as web como HTML, CSS, JS, TS o Angular.
  
  --

  ğŸ§°â€â€â€ â€ La automatizaciÃ³n y el CI/CD me encantan; por ello me escucharÃ¡s a menudo hablar de Jenkins y Sonar o sobre diferentes plataformas como AWS, Azure o GCP.

  --

  ğŸ¦„ â€ Me gustan mucho los temas relacionados con arquitectura y buenas prÃ¡cticas asÃ­ que no dudes en charlar conmigo sobre DDD, arquitectura hexagonal o SOLID.
  
  --

  ğŸ¤¯â€â€â€ â€  Soy un apasionado de la tecnologÃ­a aparte de Ã¡vido lector y profesional del sarcasmo.
  
  --
  
  ğŸ‘‡ğŸ» â€ MÃ¡s informaciÃ³n aquÃ­.
  """

  [[params.socialIcons]]
  name = "twitter"
  url = "https://twitter.com/marcosDLCS"

  [[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/marcosdlcs/"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/marcosDLCS"
